# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ft7eyBQ7qIG-rwixXHZ2zwLtqcmrsWOe
"""

# declare and assign list1
mylist = range(21)

# declare listOdd - to store odd numbers
# declare listEven - to store even numbers
listOdd = []
listEven = []
listDouble = []

# check and append odd numbers in listOdd
# and even numbers in listEven
for i in mylist:
	if i%2 == 0:
		listEven.append(i)
	else:
		listOdd.append(i) 

# print lists
print(listEven)
print(listOdd)
#merge two lists
newlist = listOdd + listEven
print(newlist)
listDouble = [i*2 for i in newlist]
print(listDouble)
for j in listDouble:
  print(j , type(j))

