# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VZbSqW6okrBWiC_w26fxdMBwXzWr-_ZU
"""

cv1 = {"Name" : "Feride", "Surname" : "Yılmaz", "Gender" : "Female", "Age" : 25, "Job" : "Engineer"}
cv2 = {"Name" : "Bekircan", "Surname" : "Akpınar", "Gender" : "Male", "Age" : 25, "Job" : "Engineer"}
cv3 = {"Name" : "Enes", "Surname" : "Yakut", "Gender" : "Male", "Age" : 25, "Job" : "Economist"}
cv4 = {"Name" : "Gamze", "Surname" : "Turgut", "Gender" : "Female", "Age" : 25, "Job" : "Doctor"}
cv5 = {"Name" : "Mine", "Surname" : "Kazar", "Gender" : "Female", "Age" : 25, "Job" : "Doctor"}
for v in cv1.values():
  print(v)

for v in cv2.values():
  print(v)

for v in cv3.values():
  print(v)

for v in cv4.values():
  print(v)
  
for v in cv5.values():
  print(v)